export const KusangOptions = [
    { label: '46-Narpatganj EVM Commissioning', value: '46-Narpatganj EVM Commissioning' },
    { label: '47-Raniganj EVM Commissioning', value: '47-Raniganj EVM Commissioning' },
    { label: '48-Forbesganj EVM Commissioning', value: '48-Forbesganj EVM Commissioning' },
    { label: '49-Araria EVM Commissioning', value: '49-Araria EVM Commissioning' },
    { label: '50-Jokihat EVM Commissioning', value: '50-Jokihat EVM Commissioning' },
    { label: '51-Sikti EVM Commissioning', value: '51-Sikti EVM Commissioning' },
    { label: 'ACTIVE MEDIA GROUP', value: 'ACTIVE MEDIA GROUP' },
    { label: 'ADARSH ACHAR SANHITA', value: 'ADARSH ACHAR SANHITA' },
    { label: 'CONTROL ROOM', value: 'CONTROL ROOM' },
    { label: 'CPMF', value: 'CPMF' },
    { label: 'Computerization Cell', value: 'Computerization Cell' },
    { label: 'DEMP CELL', value: 'DEMP CELL' },
    { label: 'DISTRICT COMMUNICATION', value: 'DISTRICT COMMUNICATION' },
    { label: 'DISTRICT CONTROL', value: 'DISTRICT CONTROL' },
    { label: 'ELECTION OFFICE CELL', value: 'ELECTION OFFICE CELL' },
    { label: 'EVM/VVPAT', value: 'EVM/VVPAT' },
    { label: 'Expenditure Monitoring', value: 'Expenditure Monitoring' },
    { label: 'IT CELL', value: 'IT CELL' },
    { label: 'KARMIK CELL', value: 'KARMIK CELL' },
    { label: 'KARMIK KALYAN', value: 'KARMIK KALYAN' },
    { label: 'LAW AND ORDER', value: 'LAW AND ORDER' },
    { label: 'MAHILA COLLEGE, ARARIA', value: 'MAHILA COLLEGE, ARARIA' },
    { label: 'MAHILA COLLEGE, PURNIA', value: 'MAHILA COLLEGE, PURNIA' },
    { label: 'MATERIAL CELL', value: 'MATERIAL CELL' },
    { label: 'MEDIA /MCMC', value: 'MEDIA /MCMC' },
    { label: 'MICRO OBSERVER', value: 'MICRO OBSERVER' },
    { label: 'NOMINATION CELL', value: 'NOMINATION CELL' },
    { label: 'Postal Ballot', value: 'Postal Ballot' },
    { label: 'PWDs CELL', value: 'PWDs CELL' },
    { label: 'SECTOR MAGISTRATE', value: 'SECTOR MAGISTRATE' },
    { label: 'SINGLE WINDOW', value: 'SINGLE WINDOW' },
    { label: 'STRONG ROOM', value: 'STRONG ROOM' },
    { label: 'SWEEP', value: 'SWEEP' },
    { label: 'TRANING CELL', value: 'TRANING CELL' },
    { label: 'OTHER', value: 'OTHER' }
];